{% set name = "jarvis-tools" %}
{% set version = "2021.10.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jarvis-tools-{{ version }}.tar.gz
  sha256: 5bf6b54df811eeab0ed4fbc1ae90b06205d90639ef34215eeb3468237f2d2908

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - joblib
    - matplotlib-base
    - numpy
    - python >=3.5
    - requests
    - scipy
    - spglib
    - toolz
    - xmltodict
    - tqdm

test:
  imports:
    - jarvis
    - jarvis.ai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://jarvis.nist.gov
  summary: 'jarvis-tools: an open-source software package for data-driven atomistic materials design'
  license: NIST-PD
  license_file: LICENSE
  description: |
    NIST-JARVIS (Joint Automated Repository for Various Integrated
    Simulations) is an integrated framework for computational science
    using density functional theory, classical force-field/molecular
    dynamics and machine-learning. The jarvis-tools package consists
    of scripts used in generating and analyzing the dataset. This
    project is a part of the Materials Genome Initiative (MGI) at NIST.
  doc_url: https://jarvis-materials-design.github.io/dbdocs/
  dev_url: https://github.com/usnistgov/jarvis

extra:
  recipe-maintainers:
    - wd15
    - knc6
