{% set name = "jarvis-tools" %}
{% set version = "2024.3.24" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jarvis-tools-{{ version }}.tar.gz
  sha256: 057418647ff25ef45e1d95ac4aa0d53fa81a10115558a8039169af168d4c0394

build:
  noarch: python 
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - setuptools
    - python >=3.8
  run:
    - python >=3.8
    - setuptools
    - numpy >=1.19.5
    - scipy >=1.6.3
    - joblib
    - matplotlib-base
    - requests
    - spglib
    - toolz
    - xmltodict
    - tqdm

test:
  imports:
    - jarvis
    # - jarvis.ai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/knc6/jarvis
  summary: jarvis
  license: NIST-PD
  license_file: LICENSE
  
# about:
#   home: https://jarvis.nist.gov
#   summary: 'jarvis-tools: an open-source software package for data-driven atomistic materials design'
#   license: NIST-PD
#   license_file: LICENSE
#   description: |
#     NIST-JARVIS (Joint Automated Repository for Various Integrated
#     Simulations) is an integrated framework for computational science
#     using density functional theory, classical force-field/molecular
#     dynamics and machine-learning. The jarvis-tools package consists
#     of scripts used in generating and analyzing the dataset. This
#     project is a part of the Materials Genome Initiative (MGI) at NIST.
#   doc_url: https://pages.nist.gov/jarvis/
#   dev_url: https://github.com/usnistgov/jarvis

extra:
  recipe-maintainers:
    - wd15
    - knc6
